### ISSUE TITLE
Unable to stabilize after adding gyro

### ISSUE THREAD

**Issue by GitHubForPP** [ericstoneking/42#17]
Hi, my simulation uses the sc_simple.txt file. I added a gro to read the angular speed through the gro, but after the increase, it runs 42. The model can't be stable and has been rotating wildly. Am I using it correctly?

Here is the code I modified.

******************************* Gyro ************************************
1                                ! Number of Gyro Axes
============================== Axis 0 ===================================
0.1                           ! Sample Time,sec
1.0  0.0  0.0                 ! Axis expressed in Body Frame
1000.0                        ! Max Rate, deg/sec
100.0                         ! Scale Factor Error, ppm
1.0                           ! Quantization, arcsec 
0.07                          ! Angle Random Walk (deg/rt-hr)
0.1  1.0                      ! Bias Stability (deg/hr) over timespan (hr)
0.1                           ! Angle Noise, arcsec RMS
0.1                           ! Initial Bias (deg/hr)
0                             ! Flex Node Index

**Comment by ericstoneking** [comment]
Hi,

You have more to do to make this work.  You're moving beyond the realm of quick demos into building your own custom system.  C coding and debugging will be needed.  I also assume you know your way around ACS.
1)  You probably want three gyro axes, not just one.
2)  Adding a gyro model does not automatically add a gyro processing function. 42sensors.c:GyroModel populates SC.AC.Gyro[0:Ngyro-1].Rate.  It's up to you to map those signals to SC.AC.wbn[0:2].  Look in AcApp.c:GyroProcessing for inspiration, or make your own.
3)  My guess is that you're still using PROTOTYPE_FSW.  This controller is meant for *very* quick and dirty visualization-level work.  If you're to the point where you're adding sensor models and want to understand the resulting performance, I would suggest that it is time for you to graduate to AD_HOC_FSW.  Customize 42fsw.c:AdHocFSW to use whatever sensors and actuators you add.
4)  More to the point of the symptom you're seeing: in 42sensors.c:Sensors, look for these lines:
```
     /* Gyro */
      if (S->Ngyro == 0) {
         for (i=0;i<3;i++) AC->wbn[i] = S->B[0].wn[i];
      }
      else {
         GyroModel(S);
      }

```
As you can see, when you changed Ngyro from zero to one, it bypasses the logic that populates AC->wbn (see Nomenclature.pdf).  Your spacecraft tumbles because you get no rate signal to feed back on.

See Docs/FSW Models.pdf.  As I write this, I realize that document is outdated: the FSW struct has been replaced by the AC struct, and generic sensor models have been added.  If you can read past these differences, there are still some important points that you should read.

I hope this all helps.  Good luck with your endeavors.

Regards,
-Eric
