### ISSUE TITLE
Reaction wheel imbalance on a rigid body

### ISSUE THREAD

**Issue by LiamBruno** [ericstoneking/42#22]
Hey Eric,

I'm currently trying to model the effect of reaction wheel imbalance forces/torques on my pointing accuracy in a particular simulation configuration. I'm assuming a single rigid body containing a bundle of reaction wheels, none of which are centered at the center of mass of the body. From my understanding, all of the reaction wheel structs are in the Body[0] struct, and their body frame locations are treated as FlexNodes given in the Flex File requested in SC.txt. Therefore I have a flex file that contains the body frame locations of each wheel. I've attached the three relevant files. Do you think you could confirm that I'm setting up the simulation correctly to model RW imbalance on a rigid body? I'm a little concerned that things are being simulated that I don't want being simulated, i.e. I don't want to be simulating any flexible body dynamics and I'm concerned that I might be.

[SC.txt](https://github.com/ericstoneking/42/files/4183366/SC.txt)
[Inp_Sim.txt](https://github.com/ericstoneking/42/files/4183369/Inp_Sim.txt)
[wheel_flex.txt](https://github.com/ericstoneking/42/files/4183370/wheel_flex.txt)

Thanks,

Liam

**Comment by ericstoneking** [comment]
Hi Liam,

Overall, you're on the right track.  Your wheel_flex.txt has some formatting issues that will likely cause 42 to crash with an annoying error message.  I would recommend either of the following:

1)  Start over with your flex file, using Flex_Simple.txt as a template.  Don't throw away any of the lines with ********'s in them.  42's text-parsing smarts are very simple, and you'll throw off its rhythm if you have more or fewer lines than it expects.  I've never tried putting in zero flex modes --- it might work, though.  Or you could put in one flex mode, but with zero stiffness (non-zero mass to avoid numerical issues).

The only part of that file that you actually want, though, is the node locations so that you can turn imbalance forces into rxF torques.  Which leads to:

2)  Edit 42perturb.c:RwaImbalance, giving it the PosB for each wheel and commenting out the need for FlexActive.  If you're comfortable dipping into the code, this is the way I would go.

Regards,
-Eric
